import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import imgHomePage from '../../public/img/imgHomePage.png'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.mainHome}>  
        {/* NAVBAR */}

        <div className={styles.containerOne}>

          <div className={imgHomePage}>
            <Image
              src={imgHomePage} 
              height={400}
              width={1230}
              alt="img"

            />
            
            <div className={styles.containerTwo}>
              <h1 className={styles.TextImg}>Encontre um profissional da saúde</h1>
              <h3 className={styles.subTextImg}>Tem alguma clínica, consultório ou hospital? Invista em um profissional novo ou recém formado</h3>
              
              <div className={styles.buttonCont}>
                <button className={styles.btnImg}>Sou um profissional</button>
                <button className={styles.btnImg}>Estou buscando um profissional</button>
                {/* TROCAR OS BOTÕES NO TAILWIND */}

              </div>

            </div>
          </div>
        </div>

        <div>
          <div>
            {/* <Image 
            
            /> */}
          </div>

          <div>
            {/* <h1>Veja as especializações que mais estão sendo empregadas</h1> */}

          </div>

        </div>

      </main>
    </>
  )
}
